println "for input of 4, 0:"
println "In both cases, the user's input enters the switch starting at line 60. An input of 4 would return 'invalid option try again'."
println "If they input 0, it would set running to false, but also terminate that loop. Program ends"
println ""

println "for input of 1, john, 0"
println "if they input 1 to start, the 'createUser' method is called. That method then calls the 'requestUser' method."
println "request user turns user input 'john' to a string called result. Method is 'killed' by return,"
println "but it now holds the value of 'john'. String user is now  'john'"
println "now enters a loop, if isValidUser is currently set as false (it is). Called to boolean method at line 40 "
println "String login is now set to value of user, so string login = john"
println "this method scans each letter of 'john'. If it's not a letter or all lower case, loginIsValid becomes false"
println "That never happens, and the program returns the value of true to isValidUser"
println "it returns to the while statement at 8, but now  isValidUser is true, so it doesn't enter that loop"
println "method insertUserInDB is called and holds the parameter value of 'john', and performs this method's scope"
println "all methods finished. Returns to running loop. User inputs 0, which set running to false, but also terminate that loop. Program ends"
println ""

println "for input of 1, john smith, johnsmith, 0"
println "Program starts in the switch. Selection of 1 calls 'createUser' method."
println "This method then calls on 'requestUser' method. This method asks for user to type input"
println "user inputs 'john smith' and String result = john smith. Method returned and holds value of 'john smith' "
println "Returns to 'createUser' method which now sets String user to 'john smith' "
println "It now enters while statement containing a loop which calls on the boolean isValidUser method at line 40"
println "this method scans user for anything not a letter or lowercase letter. The space in it causes loginIsValid = false"
println "returns to method at 8, and since loginIsValid = false, it enters the loop. Tells user they've given an invalid name"
println "it sends user back to requestUser, user types in johnsmith. It redoes the loop of checking for a valid user"
println "this one is valid, so loginIsValid is never set to false. The method at 7 restarts and it does insertUserInDB's scope"
println "it returns to the case, having completed the 'createUser' method. It says to break the switch, but reenters"
println "due to it being part of the while loop. User enter's 0 which breaks the loop and sets the while loop to false, program ends"
println ""

println "for input of 2, userNotInDB, 0"
println "Program enters the while loop and goes in to the switch. Selection of 2 calls 'deleteUser' method"
println "this method calls the 'requestUser' method. It then asks for user input"
println "String result becomes whatever user types, which is 'userNotInDB', result = userNotInDB "
println "The return is called, and this method now holds the value of result"
println "deleteUser then goes on, sets string user to = result. user = 'userNotInDB' "
println "It now enters while statement containing a loop which calls on the boolean isValidUser method at line 40"
println "this method checks to see if all the parameters are met, but they are not, because there are capital letters"
println "loginIsValid is set to false and it returns to deleteUser, since loginIsValid is false, it enters the loop"
println " the loop tells the user the login is invalid, and has it go back to requestUser method"
println " user enters 0, which will cause the last 5 lines here to happen again, because 0 will also cause loginIsValid = false"
println "program would need more input to close out properly"
println ""

println "for input of 1, john, 2, john, 0"
println "if they input 1 to start, the 'createUser' method is called. That method then calls the 'requestUser' method."
println "request user turns user input 'john' to a string called result. Method is 'killed' by return,"
println "but it now holds the value of 'john'. String user is now  'john'"
println "now enters a loop, if isValidUser is currently set as false (it is). Called to boolean method at line 40 "
println "String login is now set to value of user, so string login = john"
println "this method scans each letter of 'john'. If it's not a letter or all lower case, loginIsValid becomes false"
println "That never happens, and the program returns the value of true to isValidUser"
println "it returns to the while statement at 8, but now  isValidUser is true, so it doesn't enter that loop"
println "method insertUserInDB is called and holds the parameter value of 'john', and performs this method's scope"
println "it returns to the switch, having completed the 'createUser' method. It says to break the switch, but reenters"
println "due to it being part of the while loop. "
println "program again asks for user input, and user enters 2, which calls 'deleteUser' method "
println "this method calls the 'requestUser' method. It then asks for user input"
println "String result becomes whatever user types, which is 'userNotInDB', result = john "
println "The return is called, and this method now holds the value of result"
println "deleteUser then goes on, sets string user to = result. user = 'john' "
println "It now enters while statement containing a loop which calls on the boolean isValidUser method at line 40"
println "this method checks to see if all the parameters are met, and they are. So isValidUser stays true"
println "return is called, so it closes this method and it returns to 'deleteUser' method"
println "since isValidUser is true, it never enters the loop, but moves on and calls 'existsInDB' method"
println "this method runs its scope, presumably checking to see if that user exists. If it does,"
println "it would return existsInDB as true, and enter the if statement, which would then enter another method,"
println "which presumably deletes the user from the DB"
println "it finishes, and so is the deleteUser method. Returns to the case in the switch, which says to break"
println "it renenters the switch, and user inputs 0, turning the boolean to false and then progrma ends, as it doesn't reenter"
